In [2]:
import matplotlib.pyplot as plt
plt.rcParams['text.usetex']=True
%matplotlib inline
%config InlineBackend.figure_format='retina'

In [3]:
import numpy as np
import math
import pandas
import itertools

In [4]:
data=np.array([[-1, -1 ,1, -1, 1, -1, -1, 1],[-1 ,-1, -1, -1, -1, 1, -1, -1],[-1, 1, 1, -1, -1, 1, -1, 1]])
data

array([[-1, -1,  1, -1,  1, -1, -1,  1],
       [-1, -1, -1, -1, -1,  1, -1, -1],
       [-1,  1,  1, -1, -1,  1, -1,  1]])

In [5]:
def hebbiantraining(data):   #function that trains an hopfield network given a data matrix
    N=len(data[0])
    P=len(data[:,0])
    W=np.zeros((N,N))
    for k in range(P):
        for i in range(N):
            for j in range(N):
                W[i,j]+=data[k,i]*data[k,j]
    return W/N
W=hebbiantraining(data)
print(W)

[[ 0.375  0.125 -0.125  0.375  0.125 -0.125  0.375 -0.125]
 [ 0.125  0.375  0.125  0.125 -0.125  0.125  0.125  0.125]
 [-0.125  0.125  0.375 -0.125  0.125 -0.125 -0.125  0.375]
 [ 0.375  0.125 -0.125  0.375  0.125 -0.125  0.375 -0.125]
 [ 0.125 -0.125  0.125  0.125  0.375 -0.375  0.125  0.125]
 [-0.125  0.125 -0.125 -0.125 -0.375  0.375 -0.125 -0.125]
 [ 0.375  0.125 -0.125  0.375  0.125 -0.125  0.375 -0.125]
 [-0.125  0.125  0.375 -0.125  0.125 -0.125 -0.125  0.375]]


In [6]:
def recall (x,W):        # function that recalls a pattern given a new vector
    yold=np.random.rand(x.size)
    ynew=x
    count=0
    while(not np.array_equal(ynew,yold) or count <1000):  #iterazione fino a convergenza
        yold=ynew
        ynew=np.sign(W @ yold.T)
        count+=1
       

    return ynew

print(recall(data[0],W))
print(recall(data[1],W))
print(recall(data[2],W))


[-1. -1.  1. -1.  1. -1. -1.  1.]
[-1. -1. -1. -1. -1.  1. -1. -1.]
[-1.  1.  1. -1. -1.  1. -1.  1.]


In [46]:
datadist=np.array([[ 1 ,-1, 1, -1, 1, -1, -1, 1],[ 1, 1, -1, -1, -1, 1, -1, -1],[ 1, 1, 1, -1, 1, 1, -1, 1]])
print(datadist)
print(recall(datadist[0],W))
print(recall(datadist[1],W))
print(recall(datadist[2],W))
print(data)

[[ 1 -1  1 -1  1 -1 -1  1]
 [ 1  1 -1 -1 -1  1 -1 -1]
 [ 1  1  1 -1  1  1 -1  1]]
[-1. -1.  1. -1.  1. -1. -1.  1.]
[-1. -1. -1. -1. -1.  1. -1. -1.]
[-1.  1.  1. -1. -1.  1. -1.  1.]
[[-1 -1  1 -1  1 -1 -1  1]
 [-1 -1 -1 -1 -1  1 -1 -1]
 [-1  1  1 -1 -1  1 -1  1]]


In [57]:
combinazioni=list(itertools.product([-1,1],repeat=8))  #tutte le possibili combinazioni di -1 e 1
attractors=[]
for x in combinazioni:
    x=np.array(x)
    if np.array_equal(recall(x,W),x):     # x è un attrattore se è un punto fisso della funzione recall
        attractors.append(x)
attractors=np.array(attractors)
print(attractors)      # 10 attrattori

[[-1 -1 -1 -1 -1  1 -1 -1]
 [-1 -1 -1 -1  1 -1 -1 -1]
 [-1 -1  1 -1 -1  1 -1  1]
 [-1 -1  1 -1  1 -1 -1  1]
 [-1  1  1 -1 -1  1 -1  1]
 [ 1 -1 -1  1  1 -1  1 -1]
 [ 1  1 -1  1 -1  1  1 -1]
 [ 1  1 -1  1  1 -1  1 -1]
 [ 1  1  1  1 -1  1  1  1]
 [ 1  1  1  1  1 -1  1  1]]


In [60]:
x2dist=np.array([1,1,1,1,1,1,-1,-1])# i primi 5 numeri sono sbagliati
print(recall(x2dist,W))   #finisce in un altro attrattore, diverso da quelli usati in training

[ 1.  1. -1.  1.  1. -1.  1. -1.]
